# Generated by Django 3.1.5 on 2021-01-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_notebookproduct_smartphoneproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebookproduct',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='smartphoneproduct',
            old_name='Category',
            new_name='category',
        ),
    ]
