# Generated by Django 3.1.5 on 2021-01-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210117_1929'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotebookProduct',
            new_name='Notebooks',
        ),
        migrations.RenameModel(
            old_name='SmartphoneProduct',
            new_name='Smartphones',
        ),
    ]
